version: 2
formats: []  # Do not build epub and pdf

python:
  install:
    - requirements: "requirements-docs.txt"
    - method: "pip"
      path: "."

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  apt_packages:
    - libisal-dev
